spring:
  #OAuth, Spring Security 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT}
            redirect-uri: "{baseUrl}/auth/login/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # 애플리케이션 이름
  application:
    name: backend

  # MySQL 설정
  datasource:
    url: jdbc:mysql://localhost:3306/dongnae
    username: root
    password: root

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # 변경된 부분만 반영, 기존 데이터 유지
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Hibernate가 출력하는 SQL 로그를 읽기 좋은 형식으로 들여쓰기 해서 보여줌
        default_batch_fetch_size: 1000  # 연관된 엔티티들을 지연 로딩할 때 N+1 문제를 줄이기 위한 최적화 옵션

logging:
  level:
    org.hibernate.SQL: debug  # Hibernate가 실행하는 SQL 쿼리문을 로그에 출력
