spring:
  #OAuth, Spring Security 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 7da23c4aa31380826af4bd76184b7099
            client-secret: lR4mTWe0Tc3uyrCzCwBhcLlRxqFmHX1n
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  # jwt
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  # 애플리케이션 이름
  application:
    name: backend

  # MySQL 설정
  datasource:
    url: jdbc:mysql://localhost:3306/dongnae
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # 변경된 부분만 반영, 기존 데이터 유지
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Hibernate가 출력하는 SQL 로그를 읽기 좋은 형식으로 들여쓰기 해서 보여줌
        default_batch_fetch_size: 1000  # 연관된 엔티티들을 지연 로딩할 때 N+1 문제를 줄이기 위한 최적화 옵션
  mustache:
    prefix: classpath:/templates/
    suffix: .mustache
    charset: UTF-8
    check-template-location: true

  management:
    endpoints:
      web:
        exposure:
          include: health, info  # health와 info 엔드포인트 활성화
        base-path: /actuator  # DB, 디스크 등 컴포넌트별 상태 표시
    health:
      db:
        enabled: true  # 데이터베이스 헬스체크 활성화
      diskspace:
        enabled: true  # 디스크 공간 헬스체크 활성화

  # 비동기 처리 설정
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
      thread-name-prefix: "ai-news-"

  # 파일 업로드 크기 제한
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# AWS S3 - IAM 역할 사용
cloud:
  aws:
    credentials:
      access-key: AKIA4CBSYPKQXKN4UMET
      secret-key: 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
    s3:
      bucket: s13p11a708
    region:
      static: us-east-2
    stack:
      auto: false

# openAI
openai:
  api:
    key: S13P12A708-bdbeb6b5-f6b2-44bd-b53a-c8c13a9c123c
    url: https://gms.ssafy.io/gmsapi/api.openai.com/v1
    enabled: true

logging:
  level:
    org.hibernate.SQL: debug  # Hibernate가 실행하는 SQL 쿼리문을 로그에 출력
